services:
  - name: examen03
    type: web
    env: node
    build:
      dockerfile: Dockerfile
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: 
      - key: DB_NAME
        value: ecommerce_db
    port: 3000
